In [2]:
# Import libraries required for data analysis and visualization

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Load the cleaned e-commerce transaction dataset

file_path = "../data/raw/online_retail_raw.csv"


df = pd.read_csv(
    file_path,
    parse_dates=["InvoiceDate"]
)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [4]:
df.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom

In [5]:
rows , columns = df.shape

print("Number of rows:" , rows)
print("Number of columns:" , columns)

Number of rows: 1067371
Number of columns: 8

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 117.3 MB

In [7]:
df.describe()

           Quantity                 InvoiceDate         Price    Customer ID
count  1.067371e+06                     1067371  1.067371e+06  824364.000000
mean   9.938898e+00  2011-01-02 21:13:55.394029  4.649388e+00   15324.638504
min   -8.099500e+04         2009-12-01 07:45:00 -5.359436e+04   12346.000000
25%    1.000000e+00         2010-07-09 09:46:00  1.250000e+00   13975.000000
50%    3.000000e+00         2010-12-07 15:28:00  2.100000e+00   15255.000000
75%    1.000000e+01         2011-07-22 10:23:00  4.150000e+00   16797.000000
max    8.099500e+04         2011-12-09 12:50:00  3.897000e+04   18287.000000
std    1.727058e+02                         NaN  1.235531e+02    1697.464450

## Data Quality Analysis

Before performing exploratory analysis, the dataset is checked for
missing values, duplicate records, and invalid transaction values.

This step helps identify data quality issues that may affect the
accuracy of the analysis.

In [8]:
missing_values=df.isna().sum()
missing_values

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

## Removing Duplicate Records

Duplicate rows represent repeated transaction records. These records
can lead to double counting during analysis, so they are removed.

In [9]:
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(34335)

In [10]:
print("Number of duplicate rows:" , duplicate_count)

Number of duplicate rows: 34335

In [11]:
df=df.drop_duplicates()
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

## Standardizing Column Names

The original dataset contains some column names that are either generic
or contain spaces. These names are standardized to make the dataset
clearer, more descriptive, and easier to work with during analysis.

For example, `Price` represents the unit price of a product, while
`Customer ID` is renamed to a consistent format without spaces.

In [12]:
df=df.rename(columns={"Invoice":"InvoiceNo","Price":"UnitPrice","Customer ID":"CustomerID"})
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

## Handling Missing Product Descriptions

Some transaction records have missing product descriptions. Since the
product description is useful for product-level analysis, these missing
values are examined before deciding how to handle them.

The number of missing descriptions is checked to understand their impact
on the dataset.

In [13]:
df["Description"].isna().sum()

np.int64(4275)

## Removing Records with Missing Descriptions

Product descriptions are required for product-level analysis.
Since only a small number of records have missing descriptions,
these records are removed from the dataset.

This prevents incomplete product information from affecting
the analysis.

In [14]:
df[df["Description"].isna()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1060783,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,NaN,United Kingdom
1060787,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
1060793,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
1062442,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
1064015,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

In [15]:
df[df["Description"].isna()][["StockCode", "Description"]].head(10)

     StockCode Description
470      21646         NaN
3114     20683         NaN
3161     21350         NaN
3731     84292         NaN
4296     18010         NaN
4566    85049G         NaN
6378    35751C         NaN
6555    79323G         NaN
6576     21098         NaN
6581     21166         NaN

In [16]:
description_by_stockcode=df.groupby("StockCode")["Description"].first()
description_by_stockcode

StockCode
10002                  INFLATABLE POLITICAL GLOBE
10002R                       ROBOT PENCIL SHARPNER
10080                     GROOVY CACTUS INFLATABLE
10109                         BENDY COLOUR PENCILS
10120                                 DOGGY RUBBER
                               ...
gift_0001_60                                   NaN
gift_0001_70    Dotcomgiftshop Gift Voucher £70.00
gift_0001_80    Dotcomgiftshop Gift Voucher £80.00
gift_0001_90                                   NaN
m                                           Manual
Name: Description, Length: 5305, dtype: str

In [17]:
df["Description"] = df["StockCode"].map(description_by_stockcode)

In [18]:
df["Description"].isna().sum()

np.int64(363)

## Removing Unrecoverable Product Descriptions

Some product descriptions could not be recovered using the corresponding
StockCode because no valid description was available elsewhere in the
dataset.

These remaining records are removed because a missing product description
would limit product-level analysis.

In [19]:
df=df.dropna(subset='Description')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDRENS APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [20]:
df["Description"].isna().sum()

np.int64(0)

## Handling Invalid Quantity Values

The Quantity column represents the number of units involved in a transaction.
Negative quantities can occur in this dataset because of cancelled or
returned transactions.

These values should be examined before deciding how they should be handled,
so that valid cancellation information is not accidentally removed.

In [21]:
df.Quantity.min()

np.int64(-80995)

In [22]:
(df["Quantity"] <=0).sum()

np.int64(22193)

In [23]:
df["InvoiceNo"].str.startswith("C").sum()

np.int64(19104)

## Handling Invalid Unit Prices

UnitPrice represents the price of one unit of a product.
Zero or negative prices are not valid for revenue calculations,
so these values need to be identified before calculating revenue.

Cancellation records are retained because they may be useful for
separate cancellation analysis.

In [24]:
df.UnitPrice.min()

np.float64(-53594.36)

In [25]:
(df.UnitPrice <=0 ).sum()

np.int64(5656)

In [26]:
df = df[df["UnitPrice"]>0]
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDRENS APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [27]:
df["UnitPrice"].min()

np.float64(0.001)

## Creating Revenue Feature

Revenue represents the total value of each transaction line.
It is calculated by multiplying the quantity of products sold by
the unit price.

This feature will be used later to analyze total sales, product
performance, country-wise revenue, and revenue trends over time.

In [28]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [29]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

## Creating Date and Time Features

The InvoiceDate column contains the date and time of each transaction.
Additional date and time features are created to make it easier to
analyze sales patterns across years, months, days, and hours.

These features will later help identify seasonal and time-based
purchasing patterns.

In [30]:
df["Year"] = df["InvoiceDate"].dt.year

In [31]:
df[["InvoiceDate" , "Year"]].head()

          InvoiceDate  Year
0 2009-12-01 07:45:00  2009
1 2009-12-01 07:45:00  2009
2 2009-12-01 07:45:00  2009
3 2009-12-01 07:45:00  2009
4 2009-12-01 07:45:00  2009

In [32]:
df["Month"] = df["InvoiceDate"].dt.month

In [33]:
df[["InvoiceDate" , "Month"]].head()

          InvoiceDate  Month
0 2009-12-01 07:45:00     12
1 2009-12-01 07:45:00     12
2 2009-12-01 07:45:00     12
3 2009-12-01 07:45:00     12
4 2009-12-01 07:45:00     12

In [34]:
df["MonthName"] = df["InvoiceDate"].dt.month_name()

In [35]:
df[["InvoiceDate", "MonthName"]].head()

          InvoiceDate MonthName
0 2009-12-01 07:45:00  December
1 2009-12-01 07:45:00  December
2 2009-12-01 07:45:00  December
3 2009-12-01 07:45:00  December
4 2009-12-01 07:45:00  December

In [36]:
df["Day"] = df["InvoiceDate"].dt.day

In [37]:
df[["InvoiceDate", "Day"]].head()

          InvoiceDate  Day
0 2009-12-01 07:45:00    1
1 2009-12-01 07:45:00    1
2 2009-12-01 07:45:00    1
3 2009-12-01 07:45:00    1
4 2009-12-01 07:45:00    1

In [38]:
df["DayName"] = df["InvoiceDate"].dt.day_name()

In [39]:
df[["InvoiceDate", "DayName"]].head()

          InvoiceDate  DayName
0 2009-12-01 07:45:00  Tuesday
1 2009-12-01 07:45:00  Tuesday
2 2009-12-01 07:45:00  Tuesday
3 2009-12-01 07:45:00  Tuesday
4 2009-12-01 07:45:00  Tuesday

In [40]:
df["Hour"] = df["InvoiceDate"].dt.hour

In [41]:
df[["InvoiceDate", "Hour"]].head()

          InvoiceDate  Hour
0 2009-12-01 07:45:00     7
1 2009-12-01 07:45:00     7
2 2009-12-01 07:45:00     7
3 2009-12-01 07:45:00     7
4 2009-12-01 07:45:00     7

## Creating Cancellation Flag

Some transactions in the dataset represent cancellations.
These transactions can be identified by InvoiceNo values that start
with the letter `C`.

A binary cancellation flag is created to make cancellation analysis
easier during exploratory analysis and dashboard development.

In [42]:
df["IsCancelled"] = df["InvoiceNo"].str.startswith("C")

In [43]:
df["IsCancelled"].value_counts()

IsCancelled
False    1007913
True       19104
Name: count, dtype: int64

## Final Data Quality Check

After cleaning and feature engineering, the dataset is checked again
for missing values, duplicate records, and invalid numeric values.

This final check ensures that the processed dataset is ready for
exploratory data analysis and visualization.

In [44]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     229202
Country             0
Revenue             0
Year                0
Month               0
MonthName           0
Day                 0
DayName             0
Hour                0
IsCancelled         0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(2)

In [46]:
df["Quantity"].sum() <=0

np.False_

In [47]:
df["Quantity"].sum()<=0

np.False_

## Removing Remaining Duplicate Records

After the main cleaning steps, a final duplicate check identified
a small number of duplicate records.

These duplicate records are removed to ensure that transactions
are not counted more than once during analysis.

In [48]:
df=df.drop_duplicates()

In [49]:
df.duplicated().sum()

np.int64(0)

## Handling Missing Customer IDs

Some transactions do not contain a CustomerID. These records are
retained because they still contain useful information such as
product, quantity, price, revenue, date, and country.

For customer-level analysis, records without a CustomerID will be
excluded only when customer-specific calculations are performed.

In [50]:
df.shape

(1027015, 16)

In [51]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,MonthName,Day,DayName,Hour,IsCancelled
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,December,1,Tuesday,7,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,1,Tuesday,7,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,1,Tuesday,7,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,December,1,Tuesday,7,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,December,1,Tuesday,7,False

In [52]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'Year', 'Month',
       'MonthName', 'Day', 'DayName', 'Hour', 'IsCancelled'],
      dtype='str')

In [53]:
len(df["StockCode"].value_counts().index)    # here we found the unique index of stockcode

4932

## Saving the Cleaned Dataset

The cleaned and feature-engineered dataset is saved as a CSV file
in the processed data directory.

This processed dataset will be used as the input for the next notebook,
where exploratory data analysis and visualizations will be performed.

In [54]:
df.to_csv("../data/processed/online_retail_cleaned.csv",index=False)

In [55]:
df.shape

(1027015, 16)